pygments: true
permalink: /posts/:title
auto: false
exclude: [vendor]
rdiscount:
  extensions: [smart]
name: Hacker Within, University of California, Davis
description: An initial blog and site for THW at UC Davis
twitter: hackerwithin
gravatar_url: http://www.gravatar.com/avatar/0203c034a145af6cc2576d56cdb4cf73
disqus_username: hackerwithinadmin
